[package]
name = "task_queue"
version = "0.0.1"
authors = ["Nirklav <antonvictorovich93@gmail.com>"]
description = "The implementation of the thread pool for Rust"
repository = "https://github.com/Nirklav/task_queue"
license = "MIT"
license-file = "LICENSE"

[dependencies]
